apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static1
spec:
  accessModes:
  - ReadWriteOnce #EBS comes under readwrite once
  capacity:
    storage: 30Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-086dc77871e2ecb10