kind: Pod
apiVersion: v1
metadata:
 name: annotations
 annatations:
  buildURL: "https://jenkins.com/expense/job/backend/23"
  imageregistry: "https://hub.docker.com/"
spec:
 container:
 - name: nginx
   image: nginx