kind: Pod
apiVersion: v1
metadata:
  name: nginx
spec:
containers:
- name: nginx
  image: nginx
  env:
   - name: course
     value: "Devops with aws"
   - name: triner
     value: "shivakumar"
   - name: duration
     value: "120 hours"
    