kind: Service
apiVersion: v1
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector: # labels are used as selectors
    project: expense
    component : backend
    environment: dev
    demo: lb
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007
---
kind: Pod
apiVersion: v1
metadata:
  name: backend-lb
  labels:
  #pod details we are giving that should match to above service
    project: expense
    component : backend
    environment: dev
    demo: lb
spec:
  containers:
  - name: nginx
    image: nginx