kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
# labels of deployment resource
  labels:
    app: nginx
    tier: frontend
    purpose: deployment
spec:
  replicas: 3
  selector:
    matchlabels:
      app: nginx
      tier: frontend
      purpose: deployment
#pod template
  template:
    metadata:
      labels:
       app: nginx
       tier: frontend
       purpose: deployment
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerport: 80
