kind: Pod
apiVersion: v1
metadata:
 name: sa-demo
 namespace: expense
spec:
  # one pod can contain multiple container
 ServiceAccount: expense-mysql-secret
 containers:
 - name: nginx
   image: nginx